name: CI
on: [pull_request,push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Test
      run: sbt test
    - name: Build docker image
      run: sbt -DappVersion=actions docker
    - name: Push docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hydrosphere/serving-gateway:actions
        