name: CI
on: [pull_request,push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Test
      run: sbt test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Build image
      run: sbt -DappVersion=actions docker

    # - name: Push docker image
    #   if: success()
    #   uses: manusa/actions-publish-docker@v1.1.2
    #   with:
    #     name: hydrosphere/serving-gateway
    #     tag: actions
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic   # Need an `id` for output variables
      with:
        dry_run: true
        # You can specify specifying version range for the extra plugins if you prefer.
        extra_plugins: |
          @semantic-release/changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
    - name: Do something when a new release published
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        echo ${{ steps.semantic.outputs.new_release_version }}
        echo ${{ steps.semantic.outputs.new_release_major_version }}
        echo ${{ steps.semantic.outputs.new_release_minor_version }}
        echo ${{ steps.semantic.outputs.new_release_patch_version }}