name: CI
on: [pull_request,push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Test
      run: sbt test
    - name: Build docker image
      run: sbt -DappVersion=actions docker
    - name: Publish docker image
      uses: docker://hydrosphere/serving-gateway:actions