name: ci
on:
  [pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup scala
        uses: olafurpg/setup-scala@v10
      - name: Run tests
        run: "sbt test"
        
  Static_analysis:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        with:
          args: >
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  
  Build:
    needs: [Test, Static_analysis]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup scala
      uses: olafurpg/setup-scala@v10
    - name: Build image
      run: "sbt -DappVersion=actions docker"      
